micronaut:
    application:
        name: blank
        max: 100
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**
    server:
        port: 9000
        cors:
            enabled: true
    http:
        client:
            read-timeout: 3m
    security:
        intercept-url-map:
            -   access: isAnonymous()
                pattern: /swagger/**
            -   access: isAnonymous()
                pattern: /swagger-ui/**
        authentication: bearer
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: ${JWT_GENERATOR_SIGNATURE_SECRET:`SiDPL3UYMIxD7w9TzMTquiaf3yuiRR4R6qHk7hqvdiqcvonXiVuBuus499PjQaD0`}
                generator:
                    access-token:
                        expiration: 86400   # in seconds (86400s = 24h)
                    refresh-token:
                        secret: ${JWT_GENERATOR_SIGNATURE_SECRET:`SiDPL3UYMIxD7w9TzMTquiaf3yuiRR4R6qHk7hqvdiqcvonXiVuBuus499PjQaD0`}

datasources:
    default:
        db-type: postgresql
        url: ${JDBC_URL:`jdbc:postgresql://127.0.0.1:5433/blank`}
        driverClassName: org.postgresql.Driver
        username: ${JDBC_USERNAME:postgres}
        password: ${JDBC_PASSWORD:1}

jpa:
    default:
        entity-scan:
            packages: "com.pedrozc90"
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: ${JPA_SHOW_SQL:true}
                enable_lazy_load_no_trans: true
            org:
                hibernate:
                    flushMode: COMMIT

netty:
    default:
        allocator:
            max-order: 3

jackson:
    time-zone: UTC
    serialization:
        indentOutput: true
        writeDatesAsTimestamps: false
    deserialization:
        useBigIntegerForInts: false
        failOnUnknownProperties: false

liquibase:
    enabled: true
    datasources:
        default:
            change-log: "classpath:db/liquibase-changelog.xml"
