micronaut:
    application:
        name: blank
        max: 100
    server:
        port: 36666
        cors:
            enabled: true
    http:
        client:
            read-timeout: 3m
    security:
        authentication: bearer
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: ${JWT_SECRET:`SiDPL3UYMIxD7w9TzMTquiaf3yuiRR4R6qHk7hqvdiqcvonXiVuBuus499PjQaD0`}
                generator:
                    access-token:
                        expiration: 14400
                    refresh-token:
                        secret: ${JWT_SECRET:`SiDPL3UYMIxD7w9TzMTquiaf3yuiRR4R6qHk7hqvdiqcvonXiVuBuus499PjQaD0`}

datasources:
    default:
        db-type: postgresql
        url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:blank_test}
        driverClassName: org.postgresql.Driver
        username: ${DB_USER:postgres}
        password: ${DB_PASS:postgres}

jpa:
    default:
        entity-scan:
            packages: "com.pedrozc90"
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: ${JPA_SHOW_SQL:true}
                enable_lazy_load_no_trans: true
            org:
                hibernate:
                    flushMode: COMMIT

netty:
    default:
        allocator:
            max-order: 3

jackson:
    time-zone: UTC
    serialization:
        indentOutput: true
        writeDatesAsTimestamps: false
    deserialization:
        useBigIntegerForInts: false
        failOnUnknownProperties: false

liquibase:
    enabled: true
    datasources:
        default:
            change-log: "classpath:db/liquibase-changelog.xml"
